# Generated by Django 4.1 on 2022-09-06 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_book_cover_url_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='list_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlist',
            name='books_list',
            field=models.ManyToManyField(blank=True, related_name='books_set', to='main.book'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
