# Generated by Django 4.1 on 2022-09-06 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_userlist_list_name_alter_userlist_books_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
