# Generated by Django 4.1 on 2022-09-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userlist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_url',
            field=models.URLField(blank=True),
        ),
    ]
