# Generated by Django 4.1 on 2022-09-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_book_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='portrait_url',
            field=models.URLField(blank=True),
        ),
    ]
