# Generated by Django 4.1 on 2022-09-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_reviews_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
